application: turgleapi
version: 1
runtime: python
api_version: 1

handlers:
- url: /
  static_files: static/index.html
  upload: static/index.html

- url: /index\.html
  static_files: static/index.html
  upload: static/index.html

- url: /style\.css
  static_files: static/style.css
  upload: static/style.css

- url: /script\.js
  static_files: static/script.js
  upload: static/script.js

- url: /api/(question|answers)
  script: api.py
