application: turgleapi
version: 1
runtime: python
api_version: 1

handlers:
- url: /humans\.png
  static_files: static/humans.png
  upload: static/humans.png

- url: /
  static_files: static/index.html
  upload: static/index.html

- url: /index\.html
  static_files: static/index.html
  upload: static/index.html

- url: /style\.css
  static_files: static/style.css
  upload: static/style.css

- url: /script\.js
  static_files: static/script.js
  upload: static/script.js

- url: /(light|dark)-gear\.png
  static_files: static/\1-gear.png
  upload: static/(light|dark)-gear.png

- url: /api/(question|answers)
  script: api.py
